{
    "auth": {
        "oauth2": {
            "scopes": {
                "https://www.googleapis.com/auth/photoslibrary": {
                    "description": "See, upload, and organize items in your Google Photos library"
                },
                "https://www.googleapis.com/auth/photoslibrary.appendonly": {
                    "description": "Add to your Google Photos library"
                },
                "https://www.googleapis.com/auth/photoslibrary.edit.appcreateddata": {
                    "description": "Edit the info in your photos, videos, and albums created within this app, including titles, descriptions, and covers"
                },
                "https://www.googleapis.com/auth/photoslibrary.readonly": {
                    "description": "View your Google Photos library"
                },
                "https://www.googleapis.com/auth/photoslibrary.readonly.appcreateddata": {
                    "description": "Manage photos added by this app"
                },
                "https://www.googleapis.com/auth/photoslibrary.sharing": {
                    "description": "Manage and add to shared albums on your behalf"
                }
            }
        }
    },
    "basePath": "",
    "baseUrl": "https://photoslibrary.googleapis.com/",
    "batchPath": "batch",
    "canonicalName": "Photos Library",
    "description": "Manage photos, videos, and albums in Google Photos ",
    "discoveryVersion": "v1",
    "documentationLink": "https://developers.google.com/photos/",
    "fullyEncodeReservedExpansion": true,
    "id": "photoslibrary:v1",
    "kind": "discovery#restDescription",
    "mtlsRootUrl": "https://photoslibrary.mtls.googleapis.com/",
    "name": "photoslibrary",
    "ownerDomain": "google.com",
    "ownerName": "Google",
    "protocol": "rest",
    "resources": {
        "albums": {
            "methods": {
                "addEnrichment": {
                    "description": "Adds an enrichment at a specified position in a defined album.",
                    "flatPath": "v1/albums/{albumsId}:addEnrichment",
                    "httpMethod": "POST",
                    "id": "photoslibrary.albums.addEnrichment",
                    "path": "v1/albums/{+albumId}:addEnrichment",
                    "scopes": [
                        "https://www.googleapis.com/auth/photoslibrary",
                        "https://www.googleapis.com/auth/photoslibrary.appendonly",
                        "https://www.googleapis.com/auth/photoslibrary.sharing"
                    ]
                },
                "batchAddMediaItems": {
                    "description": "Adds one or more media items in a user's Google Photos library to an album. The media items and albums must have been created by the developer via the API. Media items are added to the end of the album. If multiple media items are given, they are added in the order specified in this call. Each album can contain up to 20,000 media items. Only media items that are in the user's library can be added to an album. For albums that are shared, the album must either b[...]",
                    "flatPath": "v1/albums/{albumsId}:batchAddMediaItems",
                    "httpMethod": "POST",
                    "id": "photoslibrary.albums.batchAddMediaItems",
                    "path": "v1/albums/{+albumId}:batchAddMediaItems",
                    "scopes": [
                        "https://www.googleapis.com/auth/photoslibrary",
                        "https://www.googleapis.com/auth/photoslibrary.appendonly",
                        "https://www.googleapis.com/auth/photoslibrary.sharing"
                    ]
                },
                "batchRemoveMediaItems": {
                    "description": "Removes one or more media items from a specified album. The media items and the album must have been created by the developer via the API. For albums that are shared, this action is only supported for media items that were added to the album by this user, or for all media items if the album was created by this user. Partial success is not supported. The entire request will fail and no action will be performed on the album if an invalid media item or album is s[...]",
                    "flatPath": "v1/albums/{albumsId}:batchRemoveMediaItems",
                    "httpMethod": "POST",
                    "id": "photoslibrary.albums.batchRemoveMediaItems",
                    "path": "v1/albums/{+albumId}:batchRemoveMediaItems",
                    "scopes": [
                        "https://www.googleapis.com/auth/photoslibrary"
                    ]
                },
                "create": {
                    "description": "Creates an album in a user's Google Photos library.",
                    "flatPath": "v1/albums",
                    "httpMethod": "POST",
                    "id": "photoslibrary.albums.create",
                    "path": "v1/albums",
                    "scopes": [
                        "https://www.googleapis.com/auth/photoslibrary",
                        "https://www.googleapis.com/auth/photoslibrary.appendonly",
                        "https://www.googleapis.com/auth/photoslibrary.sharing"
                    ]
                },
                "get": {
                    "description": "Returns the album based on the specified `albumId`. The `albumId` must be the ID of an album owned by the user or a shared album that the user has joined.",
                    "flatPath": "v1/albums/{albumsId}",
                    "httpMethod": "GET",
                    "id": "photoslibrary.albums.get",
                    "path": "v1/albums/{+albumId}",
                    "scopes": [
                        "https://www.googleapis.com/auth/photoslibrary",
                        "https://www.googleapis.com/auth/photoslibrary.readonly",
                        "https://www.googleapis.com/auth/photoslibrary.readonly.appcreateddata"
                    ]
                },
                "list": {
                    "description": "Lists all albums shown to a user in the Albums tab of the Google Photos app.",
                    "flatPath": "v1/albums",
                    "httpMethod": "GET",
                    "id": "photoslibrary.albums.list",
                    "path": "v1/albums",
                    "scopes": [
                        "https://www.googleapis.com/auth/photoslibrary",
                        "https://www.googleapis.com/auth/photoslibrary.readonly",
                        "https://www.googleapis.com/auth/photoslibrary.readonly.appcreateddata"
                    ]
                },
                "patch": {
                    "description": "Update the album with the specified `id`. Only the `id`, `title` and `cover_photo_media_item_id` fields of the album are read. The album must have been created by the developer via the API and must be owned by the user.",
                    "flatPath": "v1/albums/{albumsId}",
                    "httpMethod": "PATCH",
                    "id": "photoslibrary.albums.patch",
                    "path": "v1/albums/{+id}",
                    "scopes": [
                        "https://www.googleapis.com/auth/photoslibrary.edit.appcreateddata"
                    ]
                },
                "share": {
                    "description": "Marks an album as shared and accessible to other users. This action can only be performed on albums which were created by the developer via the API.",
                    "flatPath": "v1/albums/{albumsId}:share",
                    "httpMethod": "POST",
                    "id": "photoslibrary.albums.share",
                    "path": "v1/albums/{+albumId}:share",
                    "scopes": [
                        "https://www.googleapis.com/auth/photoslibrary.sharing"
                    ]
                },
                "unshare": {
                    "description": "Marks a previously shared album as private. This means that the album is no longer shared and all the non-owners will lose access to the album. All non-owner content will be removed from the album. If a non-owner has previously added the album to their library, they will retain all photos in their library. This action can only be performed on albums which were created by the developer via the API.",
                    "flatPath": "v1/albums/{albumsId}:unshare",
                    "httpMethod": "POST",
                    "id": "photoslibrary.albums.unshare",
                    "path": "v1/albums/{+albumId}:unshare",
                    "scopes": [
                        "https://www.googleapis.com/auth/photoslibrary.sharing"
                    ]
                }
            }
        },
        "mediaItems": {
            "methods": {
                "batchCreate": {
                    "description": "Creates one or more media items in a user's Google Photos library. This is the second step for creating a media item. For details regarding Step 1, uploading the raw bytes to a Google Server, see Uploading media. This call adds the media item to the library. If an album `id` is specified, the call adds the media item to the album too. Each album can contain up to 20,000 media items. By default, the media item will be added to the end of the library or album. I[...]",
                    "flatPath": "v1/mediaItems:batchCreate",
                    "httpMethod": "POST",
                    "id": "photoslibrary.mediaItems.batchCreate",
                    "path": "v1/mediaItems:batchCreate",
                    "scopes": [
                        "https://www.googleapis.com/auth/photoslibrary",
                        "https://www.googleapis.com/auth/photoslibrary.appendonly",
                        "https://www.googleapis.com/auth/photoslibrary.sharing"
                    ]
                },
                "batchGet": {
                    "description": "Returns the list of media items for the specified media item identifiers. Items are returned in the same order as the supplied identifiers.",
                    "flatPath": "v1/mediaItems:batchGet",
                    "httpMethod": "GET",
                    "id": "photoslibrary.mediaItems.batchGet",
                    "path": "v1/mediaItems:batchGet",
                    "scopes": [
                        "https://www.googleapis.com/auth/photoslibrary",
                        "https://www.googleapis.com/auth/photoslibrary.readonly",
                        "https://www.googleapis.com/auth/photoslibrary.readonly.appcreateddata"
                    ]
                },
                "get": {
                    "description": "Returns the media item for the specified media item identifier.",
                    "flatPath": "v1/mediaItems/{mediaItemsId}",
                    "httpMethod": "GET",
                    "id": "photoslibrary.mediaItems.get",
                    "path": "v1/mediaItems/{+mediaItemId}",
                    "scopes": [
                        "https://www.googleapis.com/auth/photoslibrary",
                        "https://www.googleapis.com/auth/photoslibrary.readonly",
                        "https://www.googleapis.com/auth/photoslibrary.readonly.appcreateddata"
                    ]
                },
                "list": {
                    "description": "List all media items from a user's Google Photos library.",
                    "flatPath": "v1/mediaItems",
                    "httpMethod": "GET",
                    "id": "photoslibrary.mediaItems.list",
                    "path": "v1/mediaItems",
                    "scopes": [
                        "https://www.googleapis.com/auth/photoslibrary",
                        "https://www.googleapis.com/auth/photoslibrary.readonly",
                        "https://www.googleapis.com/auth/photoslibrary.readonly.appcreateddata"
                    ]
                },
                "patch": {
                    "description": "Update the media item with the specified `id`. Only the `id` and `description` fields of the media item are read. The media item must have been created by the developer via the API and must be owned by the user.",
                    "flatPath": "v1/mediaItems/{mediaItemsId}",
                    "httpMethod": "PATCH",
                    "id": "photoslibrary.mediaItems.patch",
                    "path": "v1/mediaItems/{+id}",
                    "scopes": [
                        "https://www.googleapis.com/auth/photoslibrary.edit.appcreateddata"
                    ]
                },
                "search": {
                    "description": "Searches for media items in a user's Google Photos library. If no filters are set, then all media items in the user's library are returned. If an album is set, all media items in the specified album are returned. If filters are specified, media items that match the filters from the user's library are listed. If you set both the album and the filters, the request results in an error.",
                    "flatPath": "v1/mediaItems:search",
                    "httpMethod": "POST",
                    "id": "photoslibrary.mediaItems.search",
                    "path": "v1/mediaItems:search",
                    "scopes": [
                        "https://www.googleapis.com/auth/photoslibrary",
                        "https://www.googleapis.com/auth/photoslibrary.readonly",
                        "https://www.googleapis.com/auth/photoslibrary.readonly.appcreateddata"
                    ]
                }
            }
        },
        "sharedAlbums": {
            "methods": {
                "get": {
                    "description": "Returns the album based on the specified `shareToken`.",
                    "flatPath": "v1/sharedAlbums/{sharedAlbumsId}",
                    "httpMethod": "GET",
                    "id": "photoslibrary.sharedAlbums.get",
                    "path": "v1/sharedAlbums/{+shareToken}",
                    "scopes": [
                        "https://www.googleapis.com/auth/photoslibrary.sharing"
                    ]
                },
                "join": {
                    "description": "Joins a shared album on behalf of the Google Photos user.",
                    "flatPath": "v1/sharedAlbums:join",
                    "httpMethod": "POST",
                    "id": "photoslibrary.sharedAlbums.join",
                    "path": "v1/sharedAlbums:join",
                    "scopes": [
                        "https://www.googleapis.com/auth/photoslibrary.sharing"
                    ]
                },
                "leave": {
                    "description": "Leaves a previously-joined shared album on behalf of the Google Photos user. The user must not own this album.",
                    "flatPath": "v1/sharedAlbums:leave",
                    "httpMethod": "POST",
                    "id": "photoslibrary.sharedAlbums.leave",
                    "path": "v1/sharedAlbums:leave",
                    "scopes": [
                        "https://www.googleapis.com/auth/photoslibrary.sharing"
                    ]
                },
                "list": {
                    "description": "Lists all shared albums available in the Sharing tab of the user's Google Photos app.",
                    "flatPath": "v1/sharedAlbums",
                    "httpMethod": "GET",
                    "id": "photoslibrary.sharedAlbums.list",
                    "path": "v1/sharedAlbums",
                    "scopes": [
                        "https://www.googleapis.com/auth/photoslibrary",
                        "https://www.googleapis.com/auth/photoslibrary.readonly",
                        "https://www.googleapis.com/auth/photoslibrary.readonly.appcreateddata"
                    ]
                }
            }
        }
    },
    "revision": "20240626",
    "rootUrl": "https://photoslibrary.googleapis.com/",
    "servicePath": "",
    "title": "Photos Library API",
    "version": "v1",
    "version_module": true
}