{
  "revision": "20180924",
  "id": "photoslibrary:v1",
  "documentationLink": "https://developers.google.com/photos/",
  "discoveryVersion": "v1",
  "version_module": true,
  "protocol": "rest",
  "canonicalName": "Photos Library",
  "auth": {
    "oauth2": {
      "scopes": {
        "https://www.googleapis.com/auth/photoslibrary": {
          "description": "View and manage your Google Photos library"
        },
        "https://www.googleapis.com/auth/photoslibrary.readonly": {
          "description": "View your Google Photos library"
        },
        "https://www.googleapis.com/auth/photoslibrary.readonly.appcreateddata": {
          "description": "Manage photos added by this app"
        },
        "https://www.googleapis.com/auth/photoslibrary.appendonly": {
          "description": "Add to your Google Photos library"
        },
        "https://www.googleapis.com/auth/photoslibrary.sharing": {
          "description": "Manage and add to shared albums on your behalf"
        }
      }
    }
  },
  "rootUrl": "https://photoslibrary.googleapis.com/",
  "ownerDomain": "google.com",
  "name": "photoslibrary",
  "batchPath": "batch",
  "fullyEncodeReservedExpansion": true,
  "title": "Photos Library API",
  "ownerName": "Google",
  "resources": {
    "sharedAlbums": {
      "methods": {
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/photoslibrary",
            "https://www.googleapis.com/auth/photoslibrary.readonly",
            "https://www.googleapis.com/auth/photoslibrary.readonly.appcreateddata",
            "https://www.googleapis.com/auth/photoslibrary.sharing"
          ],
          "flatPath": "v1/sharedAlbums/{sharedAlbumsId}",
          "id": "photoslibrary.sharedAlbums.get",
          "path": "v1/sharedAlbums/{+shareToken}",
          "description": "Returns the album based on the specified `albumId` or `shareToken`.\nExactly one of `albumId` and `shareToken` must be set.\nThe `albumId` should be the ID of an album owned by the user or a shared\nalbum that the user has joined.",
          "httpMethod": "GET"
        },
        "list": {
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/photoslibrary",
            "https://www.googleapis.com/auth/photoslibrary.readonly",
            "https://www.googleapis.com/auth/photoslibrary.readonly.appcreateddata"
          ],
          "flatPath": "v1/sharedAlbums",
          "path": "v1/sharedAlbums",
          "id": "photoslibrary.sharedAlbums.list",
          "description": "Lists all shared albums available in the Sharing tab of the\nuser's Google Photos app."
        },
        "join": {
          "description": "Joins a shared album on behalf of the Google Photos user.",
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/photoslibrary.sharing"
          ],
          "flatPath": "v1/sharedAlbums:join",
          "path": "v1/sharedAlbums:join",
          "id": "photoslibrary.sharedAlbums.join"
        }
      }
    },
    "albums": {
      "methods": {
        "list": {
          "path": "v1/albums",
          "id": "photoslibrary.albums.list",
          "description": "Lists all albums shown to a user in the Albums tab of the Google\nPhotos app.",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/photoslibrary",
            "https://www.googleapis.com/auth/photoslibrary.readonly",
            "https://www.googleapis.com/auth/photoslibrary.readonly.appcreateddata"
          ],
          "flatPath": "v1/albums"
        },
        "get": {
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/photoslibrary",
            "https://www.googleapis.com/auth/photoslibrary.readonly",
            "https://www.googleapis.com/auth/photoslibrary.readonly.appcreateddata",
            "https://www.googleapis.com/auth/photoslibrary.sharing"
          ],
          "flatPath": "v1/albums/{albumsId}",
          "path": "v1/albums/{+albumId}",
          "id": "photoslibrary.albums.get",
          "description": "Returns the album based on the specified `albumId` or `shareToken`.\nExactly one of `albumId` and `shareToken` must be set.\nThe `albumId` should be the ID of an album owned by the user or a shared\nalbum that the user has joined."
        },
        "addEnrichment": {
          "flatPath": "v1/albums/{albumsId}:addEnrichment",
          "path": "v1/albums/{+albumId}:addEnrichment",
          "id": "photoslibrary.albums.addEnrichment",
          "description": "Adds an enrichment at a specified position in a defined album.",
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/photoslibrary",
            "https://www.googleapis.com/auth/photoslibrary.appendonly",
            "https://www.googleapis.com/auth/photoslibrary.sharing"
          ]
        },
        "create": {
          "id": "photoslibrary.albums.create",
          "path": "v1/albums",
          "description": "Creates an album in a user's Google Photos library.",
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/photoslibrary",
            "https://www.googleapis.com/auth/photoslibrary.appendonly",
            "https://www.googleapis.com/auth/photoslibrary.sharing"
          ],
          "flatPath": "v1/albums"
        },
        "share": {
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/photoslibrary.sharing"
          ],
          "flatPath": "v1/albums/{albumsId}:share",
          "path": "v1/albums/{+albumId}:share",
          "id": "photoslibrary.albums.share",
          "description": "Marks an album as shared and accessible to other users. This action can\nonly be performed on albums which were created by the developer via the\nAPI."
        }
      }
    },
    "mediaItems": {
      "methods": {
        "batchCreate": {
          "path": "v1/mediaItems:batchCreate",
          "id": "photoslibrary.mediaItems.batchCreate",
          "description": "Creates one or more media items in a user's Google Photos library.\n\nThis is the second step for creating a media item. For details regarding\nStep 1, uploading the raw bytes to a Google Server, see\n\u003ca href=\"/photos/library/guides/upload-media\"\u003eUploading media\u003c/a\u003e.\n\nThis call adds the media item to the library. If an album `id` is\nspecified, the call adds the media item to the album too. By default, the\nmedia item will be added to the end of [...]",
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/photoslibrary",
            "https://www.googleapis.com/auth/photoslibrary.appendonly",
            "https://www.googleapis.com/auth/photoslibrary.sharing"
          ],
          "flatPath": "v1/mediaItems:batchCreate"
        },
        "search": {
          "description": "Searches for media items in a user's Google Photos library.\nIf no filters are set, then all media items in the user's library are\nreturned.\nIf an album is set, all media items in the specified album are returned.\nIf filters are specified, media items that match the filters from the user's\nlibrary are listed.\nIf you set both the album and the filters, the request results in an error.",
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/photoslibrary",
            "https://www.googleapis.com/auth/photoslibrary.readonly",
            "https://www.googleapis.com/auth/photoslibrary.readonly.appcreateddata"
          ],
          "flatPath": "v1/mediaItems:search",
          "path": "v1/mediaItems:search",
          "id": "photoslibrary.mediaItems.search"
        },
        "list": {
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/photoslibrary",
            "https://www.googleapis.com/auth/photoslibrary.readonly",
            "https://www.googleapis.com/auth/photoslibrary.readonly.appcreateddata"
          ],
          "flatPath": "v1/mediaItems",
          "path": "v1/mediaItems",
          "id": "photoslibrary.mediaItems.list",
          "description": "List all media items from a user's Google Photos library."
        },
        "get": {
          "description": "Returns the media item for the specified media item `id`.",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/photoslibrary",
            "https://www.googleapis.com/auth/photoslibrary.readonly",
            "https://www.googleapis.com/auth/photoslibrary.readonly.appcreateddata"
          ],
          "flatPath": "v1/mediaItems/{mediaItemsId}",
          "id": "photoslibrary.mediaItems.get",
          "path": "v1/mediaItems/{+mediaItemId}"
        }
      }
    }
  },
  "version": "v1",
  "baseUrl": "https://photoslibrary.googleapis.com/",
  "kind": "discovery#restDescription",
  "description": "Manage photos, videos, and albums in Google Photos\n",
  "servicePath": "",
  "basePath": ""
}
