<%! import util %>\
<%def name="docs()">\
TODO: Library level fully fledged documentation, incuding **summary** and **usage**.
</%def>

<%def name="license()">\
# License
The **${util.library_name(name, version)}** library was generated by ${util.put_and(copyright.authors)}, and is placed 
under the *${copyright.license_abbrev}* license.
You can read the full text at the repository's [license file][repo-license].

[repo-license]: ${cargo.repo_base_url + 'LICENSE.md'}
</%def>